config/routes.rb
AroundYoga::Application.routes.draw do



  ## authorization
  devise_for :users,
    path: "",
    controllers: {
      sessions:           "users/sessions",
      passwords:          "users/passwords",
      confirmations:      "users/confirmations",
      omniauth_callbacks: "users/o_auth_callbacks",
      unlocks:            "users/unlocks",
      registrations:      "users/registrations"
    },
=begin
    skip: [
      :registrations
    ],
=end

    path_names: {
      sign_in:      'login',
      sign_out:     'logout',
      confirmation: 'verification',
    }


  post 'register',     to: "home#register", as: :register, format: false
  post 'create_user',  to: "home#create_user", as: :create_user, format: false

  match "/cities/autocomplete/:first_char" =>         "cities#autocomplete"
  match "/regions/fetch_regions/:country" =>          "regions#fetch_regions"
  match "/cities/fetch_cities/:country/:region" =>    "cities#fetch_cities"
  match "/interests/create/:interest" =>              "interests#create", :as => "creating"
  match "/interests/autocomplete/:first_char" =>      "interests#autocomplete"
  match "/events/autocomplete/:first_char" =>      "events#autocomplete"
  match "/groups/autocomplete/:first_char" =>      "groups#autocomplete"
  # match "/places/change_regions/:country" => "places#change_regions"

=begin  (current)
  ## resources
  resources :cities, format: false, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get   :autocomplete, on: :collection, format: false
  end
  

  resource  :strange,     format: false, path: :agree, only: [:edit, :update]
  resources :groups,      format: false
  resources :events,      format: false
  resources :discoveries, format: false
=end
  ## places
  resources :countries,   format: false, only: :show do
    resources :regions,   format: false, only: :show do
      resources :cities,  format: false, only: :show
    end
    get 'show_all_on_place',        on: :collection
  end
  

  ## static pages
  get 'about-us',         to: "pages#about_us",         as: :about_us,        format: false
  get 'contact-us',       to: "pages#contact_us",       as: :contact_us,      format: false
  get 'terms',            to: "pages#terms",            as: :terms,           format: false
  get 'advertisers',      to: "pages#advertisers",      as: :advertisers,     format: false
  get 'help',             to: "pages#help",             as: :help,            format: false
  get 'privacy-policy',   to: "pages#privacy_policy",   as: :privacy_policy,  format: false
  get 'user-agreement',   to: "pages#user_agreement",   as: :user_agreement,  format: false

  ## dashboard
  #current resource :dashboard, only: [:show], format: false
  get   '/dashboard',               to: 'dashboards#show'
  get   '/group_feed',              to: 'dashboards#group_feed'
  get   '/message',                 to: 'dashboards#message'
  get   '/search',                  to: 'dashboards#search'
  get   '/people',                  to: 'dashboards#people'
  get   '/pictures',                to: 'dashboards#pictures'
  get   '/picture',                 to: 'dashboards#picture'
  get   '/friendrequests',          to: 'friendship#friend_requests'
  get   '/upload_picture',          to: 'dashboards#upload_picture'
  get   '/settings',                to: 'dashboards#settings'
  post   '/update_settings',        to: 'dashboards#update_settings'
  get   '/connect_facebook',        to: 'dashboards#connect_facebook'
  get   '/inbox',                   to: 'messages#inbox'
  ## landing page
  root to: 'home#index'
  
  get '/manual_signup',             to: 'home#manual'
  
  ## resources
  resources :events, only: [:new, :create, :show, :destroy] do
    post 'attend',         on: :member
    post 'not_attend',     on: :member
    post 'share_facebook', on: :member
    get 'all',        on: :collection
    get 'my',         on: :collection  
    get 'near_city',    on: :collection
    get 'near_region',  on: :collection
    get 'near_country', on: :collection
    get 'public',     on: :collection
    get 'search',     on: :collection
  end

  resources :places, only: :index do
    get 'people',     on: :collection
    get 'change_regions',     on: :collection
  end


  resources :groups, only: [:new, :create] do
    get 'mine',       on: :collection, as: :my
    get 'users',      on: :member
    get 'members',    on: :member
    get 'about',      on: :member
    get 'groupusers', on: :collection
    get 'moderate',   on: :collection
    get 'settings',   on: :member
    # get 'discussion', on: :member
    get 'popular', on: :collection
    get 'recent', on: :collection
    get 'search',     on: :collection
    get 'council', on: :member
    get 'latest_discussions', on: :member
    get 'latest_activities',  on: :member
    post 'share_facebook', on: :member
    post 'join_group',  to: 'membership#create'
    delete 'removes_member', to: 'membership#remove'
    put 'add_as_group_leader', to: 'membership#add_as_group_leader'
    put 'remove_from_group_leader', to: 'membership#remove_from_group_leader'
    put 'block', to: 'membership#block_from_group'
    
    resources :discussions, only: [:new, :create, :show, :update] do
      resources :comments do
        post 'like', on: :collection
        
      end
    end
    
    resources :settings, only: [:create, :update]
  end

  resources :interests, only: [:index, :show, :new] do
    get 'members',    on: :member
    get 'follow',    on: :member
    get 'unfollow',    on: :member
    get 'fetch_interests', on: :collection
  end

  resources :users, only: [:show] do 
    resource  :profile, only: [:show, :edit, :update]
    resources :messages, only: [:create]
    resources :pictures, only: [:index, :create, :show, :destroy, :update] do
      resources :comments do
        post 'like', on: :collection
        
      end
      get 'upload_picture',    on: :collection
    end
    resources :activities
    resources :update_statuses
    
    post   '/friend_request',  to: 'friendship#create'
    post   '/accept',  to: 'friendship#accept', as: 'friend_request_accept'
    post   '/ignore',  to: 'friendship#ignore', as: 'friend_request_ignore'
    post   '/decline',  to: 'friendship#decline', as: 'friend_request_decline'
    get    '/friend_requests', to: 'friendship#friend_requests'
    get    '/messages', to: 'messages#messages_with_user', as: 'related_messages'
    
  end

  resource :authorization, only: [:destroy] 
  
  resources :comments, only: [:destroy] do
    post 'flag', on: :collection
  end

  
  
  
end

app/models/group.rb
class Group < ActiveRecord::Base
  
  attr_accessible :name, :description, :tag, :ettiquette
  has_many :memberships, dependent: :destroy
  has_many :members,
           :through => :memberships,
           :source => :user,
           :conditions => "member_type = 'member' and status <> 'blocked'"
           
  has_many :owners,
           :through => :memberships,
           :source => :user,
           :conditions => "member_type = 'owner' and status <> 'blocked'"
           

  has_many :leaders,
           :through => :memberships,
           :source => :user,
           :conditions => "member_type = 'leader' and status <> 'blocked'"
           
  has_many :users,
           :through => :memberships,
           :source => :user,
           :conditions => "status <> 'blocked'"
           
  has_many :discussions, dependent: :destroy
  
  has_one  :setting
  
  attr_accessible :avatar
  
  has_attached_file :avatar, :styles => { :medium => "110x110>", :small => "97x97>", :main => "40x40>" }
  

end

app/controllers/groups_controller.rb
# class GroupsController < SecureController
class GroupsController < ApplicationController
  include GroupsHelper
  before_filter :authenticate_user! 
  before_filter :discussion_parameters_setup, :only => [:latest_discussions, :latest_activities] 
  before_filter :members_parameters_setup,    :only => [:users, :council, :about, :settings]
  
  def latest_discussions

    @latest_discussions = @discussions.order('created_at DESC')    
    @render_type = 'latest_discussions'
    @discussion = Discussion.new
    render 'discussion_layout'
  end
  
  def latest_activities

    @latest_activities = @discussions.order('last_activity_at DESC')   
    @render_type = 'latest_activities'
    @discussion = Discussion.new
    render 'discussion_layout'
  end
  
  
  def new
    @group = Group.new
  end

  def create
    puts "created ok!!!!!!!!!!!!!!!!"
    @user = current_user
    unless params[:group][:name].empty?
      unless Group.find_by_name(params[:group][:name])
        @group = Group.new(params[:group])
        @group.save!
        
        # create activity to start a group
        create_activity(current_user.id, "started", "Group", @group.id)
        
        membership = Membership.new
        membership.user = @user
        membership.group = @group
        membership.member_type = 'owner'
        membership.save!
        
        @group.setting = Setting.new(:auto_removed => true, :flag_count => 5)
        
        redirect_to :action => :popular and return
      end
    end
    redirect_to :back 
  end
  
  def mine
    @user = current_user
    @groups = @user.groups
    @owner_groups = @user.owner_groups
    @moderator_groups = @user.moderator_groups
    @member_groups = @user.member_groups
    
    @render_type = 'mine'
    
    render 'groups_layout'
  end
  
  def popular
    @render_type = 'popular'
    @popular_groups = popular_groups(Group.all) 
       
    render 'groups_layout'
  end
  
  def recent
    @render_type = 'recent'
    @recent_groups = Group.order('created_at DESC')
    render 'groups_layout'
  end
  
  # users = members
  def users
    
    @render_type = 'members'
    render 'users_layout'
  end
  
  def council
    @leaders = @group.leaders
    
    @render_type = 'council'
    render 'users_layout'
  end
  
  def about
    @render_type = 'about'
    render 'users_layout'   
  end
  
  def settings
    
    @group.setting ||= Setting.new
    @setting = @group.setting
    
    @render_type = 'settings'
    render 'users_layout'   
    
  end
  
  def search
    
    query = params[:search_query]
    if @group = Group.where('lower(name) = ?', query.downcase).first
      @user = current_user    
      @joined_state = !Membership.find_by_user_id_and_group_id(@user.id, @group.id).nil?
      @users = @group.users
      @owners = @group.owners   
      @leaders = @group.leaders
      @discussions = @group.discussions
      @latest_discussions = @discussions.order('created_at DESC')    
      @render_type = 'latest_discussions'
      @discussion = Discussion.new
      render 'discussion_layout' and return
    else
      redirect_to :back 
    end
  end  
  
  def autocomplete

    first_char = params[:first_char]
    
    groups = Group.where('lower(name) like ?', "%#{first_char.downcase}%")
        
    
    @groups_name = []
    groups.each do |group|
      @groups_name << group.name
    end
    
    respond_to do |format|      
      format.json  { render :json => @groups_name }
    end      
  end
  
  def share_facebook
    @group = Group.find(params[:id])
    access_token = current_user.authorizations.first.access_token
    me = FbGraph::User.me(access_token)
    puts latest_discussions_group_url(@group)
    me.feed!(
      :message => 'Updating via AroundYoga',
      # :picture => asset_path("around_yoga_icon320.png"),
      :link => latest_discussions_group_url(@group),
      :name => @group.name,
      :description => @group.description
    )
    redirect_to :back
  end  
  
  private
  
  def discussion_parameters_setup
    @group = Group.find(params[:id])
    @discussions = @group.discussions
    @user = current_user
    @joined_state = !Membership.find_by_user_id_and_group_id(@user.id, @group.id).nil?
    @users = @group.users
    @owners = @group.owners   
    @leaders = @group.leaders
  
    @facebook = Authorization.where('user_id = ? and provider_id = ?',current_user.id, 1000).first
    @twitter  = Authorization.where('user_id = ? and provider_id = ?',current_user.id, 2000).first
  end 
  
  def members_parameters_setup
    @group = Group.find(params[:id])
    @user = current_user
    @joined_state = !Membership.find_by_user_id_and_group_id(@user.id, @group.id).nil?
    @users = @group.users    
    @members = @group.members
    
    @owners = @group.owners
    @editable_state = @owners.include?(@user)    
  end 
  

end

app/helpers/groups_helper.rb
module GroupsHelper
  def popular_groups(groups)    
    arr = []    
    groups.each do |group|          
      arr << {:id => group.id, :popular_size => group.users.size}
    end
    sorted_arr = arr.sort_by{|e| -e[:popular_size]}
    popular_groups = []
    sorted_arr.each do |element|
      popular_groups << Group.find(element[:id])
    end
    popular_groups
  end
  
  
  def comments_count(group)
    counts = 0
    group.discussions.each do |d|
      counts = counts + d.comments.size
    end
    counts
  end
end

app/views/groups/_about.html.haml
%section.box.boxC
 %h2
  About
 %p= group.description
%section.box.boxC
 %h2
  Ettiquette
 %p= group.ettiquette

app/views/groups/_aside_group_council.html.haml
.box.boxB
 %h2
  Group Council
 %ul.listF
  - owners.each do |owner| 
   %li
    = image_tag owner.avatar.url(:group_thumb)
    %h5
     = link_to owner.name, user_profile_path(owner)
    %span
     (Owner)
  - leaders.each do |leader|    
   %li
    = image_tag leader.avatar.url(:group_thumb)
    %h5
     = link_to leader.name, user_profile_path(leader)

app/views/groups/_council.html.haml
%section.box.boxC.namecards.noBorder.noScroll
 %ul.listE
  - owners.each do |owner|
   %li
    = image_tag owner.avatar.url, width: "81", height: "81", alt: "Avatar"
    %h2
     = link_to owner.name, user_profile_path(owner)
    %strong= owner.profile.place

  - leaders.each do |leader|
   %li
    = image_tag leader.avatar.url, width: "81", height: "81", alt: "Avatar"
    %h2
     = link_to leader.name, user_profile_path(leader)
    %strong
     Eagan, Minneapolis, USA
    - if editable_state 
     .options-wrap
      %button.mod-options
       Options
      %ul.options-list
       %li
        = link_to "Remove from group", group_removes_member_path(group, leader), :method => :delete
       %li
        = link_to "Remove from group council", group_remove_from_group_leader_path(group, leader), :method => :put
       %li
        = link_to "Block from group", group_block_path(group, leader), :method => :put

app/views/groups/_create.html.haml
= link_to new_group_path do
 %button.btn.btnB.headingButton{action: "#"}
  Create Group

app/views/groups/_group_detail.html.haml
%li
  .inner
    -# %aside
     
      -# = image_tag group.avatar.url, width: 40, height: 40, alt: ''

    .content
      %h2= link_to group.name, latest_discussions_group_path(group)
      %ul.fence
        %li<
          %span.meter{:'data-value' => 1}
            = group.users.size 
            members
        %li<
          %span.meter{:'data-value' => 1}
            = group.discussions.size
            discussions
        %li<
          %span.meter{:'data-value' => 1} 
            = comments_count(group)
            comments

    %p= group.description 

app/views/groups/_inner_header.html.haml
-# %aside
 -# .thumb
  -# = image_tag group.avatar.url, width: 40, height: 40, alt: "Avatar"
.col

 %h1= group.name  
 -# -if (page_name === "single" || page_name === "discussion")
 -if page_name === "discussion"
  %button.headingButton.discussionHead#new_discussion
   Start a Discussion
 %ul.fence
  %li.meter
   = users.size
   members
  %li
   - unless joined_state      
    =link_to "Join the Group", group_join_group_path(group), :method => :post
.book
 %nav
  %ul.tabs
   %li{class: (page_name === "users") ? "on" : ""}
    = link_to "Members", users_group_path(group)
   %li{class: (page_name === "single" || page_name === "discussion") ? "on" : ""}
    = link_to "Discussions", latest_discussions_group_path(group)
   %li{class: (page_name === "about") ? "on" : ""}
    = link_to "About/Ettiquette", about_group_path(group)
   %li{class: (page_name === "settings") ? "on" : ""}
    - if group.owners.include?(current_user) || group.leaders.include?(current_user)
     = link_to "Manage", settings_group_path(group)
  - if page_name == "users"
   %ul.subCat
    %li.on= link_to 'Members', users_group_path(group)
    %li= link_to 'Group Council', council_group_path(group)    
  - if page_name == "discussion"
   %ul.subCat
    %li.on= link_to 'Latest Discussions', latest_discussions_group_path(group)
    %li= link_to 'Latest Activities', latest_activities_group_path(group)

app/views/groups/_members.html.haml
%section.box.boxC.namecards.noBorder.noScroll
 %ul.listE
  - members.each do |member|
   %li
    = image_tag member.avatar.url, width: "81", height: "81", alt: "Avatar"
    %h2
     = link_to member.name, user_profile_path(member)
    %strong= member.profile.place
    - if editable_state 
     .options-wrap
      %button.mod-options
       Options
      %ul.options-list
       %li
        = link_to "Remove from group", group_removes_member_path(group, member), :method => :delete
       %li
        = link_to "Block from group", group_block_path(group, member), :method => :put
       %li
        = link_to "Add as group council", group_add_as_group_leader_path(group, member), :method => :put 

app/views/groups/_popular.html.haml
%section
  %ul.listC.listG
    - groups.each do |group|
      = render :partial => 'group_detail', :locals => {:group => group}
   

app/views/groups/_recent.html.haml
%section
  %ul.listC.listG
    - groups.each do |group|
      = render :partial => 'group_detail', :locals => {:group => group}
   

app/views/groups/_search.html.haml
%form.mini.search.blanket{ action: search_groups_path}
  <label for="search-groups-query" class="placeholder">Search for groups</label>
  <input type="text" name="search_query" class="text" id="group-searh-query" value="Search for groups" data-default-value="Search for groups" autocomplete="off"/>
  <input type="submit" class="button submit wide" value="Search" />

app/views/groups/_settings.html.haml
%section.moderation
 %ul.options
  %li.on
   =link_to "Settings", settings_group_path(group)  
 %div
  = form_for [group, setting], :html => { :class => 'settings-update'} do |f|   
   %div
    %label{for: "who"}
     Who can start a discussion?
    %select{name: "who"}
     %option
      Any Member
     %option
      Only Council
   %div
    %label{for: "auto-remove"}
     Automatically remove content flagged innapropriate by users?
    = f.check_box :auto_removed
   %div
    %label{for: "number-flags"}
     Number of flags:
    = f.select :flag_count, [ '5', '10', '15', '20', '25' ] 
    -# %select.numbers-select
   = f.submit "Submit", :class => 'default_button'

app/views/groups/groups_layout.html.haml
- content_for(:navigation_item) { 'Groups' }
#main.inwards.colgroup.colgroup2

  %hgroup
    %h1 Groups
    %h2 Find people around you and around the world.
    = render partial: 'create'

  .col
    .book
      = render partial: 'search'

      %ul.subCat
        %li.on= link_to 'Most Popular', popular_groups_path
        %li= link_to 'Most recent', recent_groups_path
      
      
      - case @render_type
      - when 'mine'
        = render partial: 'mine', locals: {member_groups: @member_groups, moderator_groups: @moderator_groups, owner_groups: @owner_groups}
      - when 'popular'
        = render partial: 'popular', locals: {groups: @popular_groups}
      - when 'recent'  
        = render partial: 'recent', locals: {groups: @recent_groups}

  %aside
    = render partial: 'shared/event_ads'

app/views/groups/new.html.haml
- content_for(:navigation_item) { 'Groups' }
#main.inwards.colgroup.colgroup1
  #form_wrap
    %h1 Create Group
    = form_for @group, :html => { :class => "form_default", :multipart => true } do |f|

    
      -# %aside.photo
        -# = image_tag 'thumb_180x180_amanda-stickleback.jpg', id: 'group_photo'
        
        -# = link_to 'Change photo', '#', id: 'change_group_photo'
        
        -# = f.file_field :avatar


      %label{:for => "name"} Group Name:
      = f.text_field :name
      %label{:for => "description"} Group About:
      = f.text_area :description
      %aside.interest
        %label{:for => "ettiquette"} Group Ettiquette:
        = f.text_field :ettiquette
        -# %label{for: :interests} Tags
        -# = f.text_field :tag, :id => '#add_interests.input_autocomplete', :value => 'Type an interest and press enter ...'

        -# #interest_target
          -# <span class="an_interest">Yoga <em class="remove_interest">x</em></span>
          -# <span class="an_interest">Healthy Living <em class="remove_interest">x</em></span>


      = f.submit "Create Group", :class => 'default_button'

app/views/groups/users_layout.html.haml
- content_for(:navigation_item) { 'Groups' }
#main.inwards.colgroup.colgroup2
 .col
  %section.colgroup.profile.profileB
   
   - case @render_type
   - when 'members'
    = render :partial => "inner_header", :locals => {:page_name => "users", :group => @group, :joined_state => @joined_state, users: @users}
    = render partial: 'members', :locals => {:members => @members, :editable_state => @editable_state, :group => @group}
   - when 'council'
    = render :partial => "inner_header", :locals => {:page_name => "users", :group => @group, :joined_state => @joined_state, users: @users}
    = render partial: 'council', :locals => {:owners => @owners, :editable_state => @editable_state, :group => @group, :leaders => @leaders, }
   - when 'about'
    = render :partial => "inner_header", :locals => {:page_name => "about", :group => @group, :joined_state => @joined_state, users: @users}
    = render partial: 'about', :locals => {:group => @group}
   - when 'settings'
    = render :partial => "inner_header", :locals => {:page_name => "settings", :group => @group, :joined_state => @joined_state, users: @users}
    = render partial: 'settings', :locals => {:group => @group, :setting => @setting}
     

  =link_to "Load More People", "#", id: "show_more"

 %aside

  = render partial: 'shared/event_ads'