config/routes.rb
AroundYoga::Application.routes.draw do



  ## authorization
  devise_for :users,
    path: "",
    controllers: {
      sessions:           "users/sessions",
      passwords:          "users/passwords",
      confirmations:      "users/confirmations",
      omniauth_callbacks: "users/o_auth_callbacks",
      unlocks:            "users/unlocks",
      registrations:      "users/registrations"
    },
=begin
    skip: [
      :registrations
    ],
=end

    path_names: {
      sign_in:      'login',
      sign_out:     'logout',
      confirmation: 'verification',
    }


  post 'register',     to: "home#register", as: :register, format: false
  post 'create_user',  to: "home#create_user", as: :create_user, format: false

  match "/cities/autocomplete/:first_char" =>         "cities#autocomplete"
  match "/regions/fetch_regions/:country" =>          "regions#fetch_regions"
  match "/cities/fetch_cities/:country/:region" =>    "cities#fetch_cities"
  match "/interests/create/:interest" =>              "interests#create", :as => "creating"
  match "/interests/autocomplete/:first_char" =>      "interests#autocomplete"
  match "/events/autocomplete/:first_char" =>      "events#autocomplete"
  match "/groups/autocomplete/:first_char" =>      "groups#autocomplete"
  # match "/places/change_regions/:country" => "places#change_regions"

=begin  (current)
  ## resources
  resources :cities, format: false, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get   :autocomplete, on: :collection, format: false
  end
  

  resource  :strange,     format: false, path: :agree, only: [:edit, :update]
  resources :groups,      format: false
  resources :events,      format: false
  resources :discoveries, format: false
=end
  ## places
  resources :countries,   format: false, only: :show do
    resources :regions,   format: false, only: :show do
      resources :cities,  format: false, only: :show
    end
    get 'show_all_on_place',        on: :collection
  end
  

  ## static pages
  get 'about-us',         to: "pages#about_us",         as: :about_us,        format: false
  get 'contact-us',       to: "pages#contact_us",       as: :contact_us,      format: false
  get 'terms',            to: "pages#terms",            as: :terms,           format: false
  get 'advertisers',      to: "pages#advertisers",      as: :advertisers,     format: false
  get 'help',             to: "pages#help",             as: :help,            format: false
  get 'privacy-policy',   to: "pages#privacy_policy",   as: :privacy_policy,  format: false
  get 'user-agreement',   to: "pages#user_agreement",   as: :user_agreement,  format: false

  ## dashboard
  #current resource :dashboard, only: [:show], format: false
  get   '/dashboard',               to: 'dashboards#show'
  get   '/group_feed',              to: 'dashboards#group_feed'
  get   '/message',                 to: 'dashboards#message'
  get   '/search',                  to: 'dashboards#search'
  get   '/people',                  to: 'dashboards#people'
  get   '/pictures',                to: 'dashboards#pictures'
  get   '/picture',                 to: 'dashboards#picture'
  get   '/friendrequests',          to: 'friendship#friend_requests'
  get   '/upload_picture',          to: 'dashboards#upload_picture'
  get   '/settings',                to: 'dashboards#settings'
  post   '/update_settings',        to: 'dashboards#update_settings'
  get   '/connect_facebook',        to: 'dashboards#connect_facebook'
  get   '/inbox',                   to: 'messages#inbox'
  ## landing page
  root to: 'home#index'
  
  get '/manual_signup',             to: 'home#manual'
  
  ## resources
  resources :events, only: [:new, :create, :show, :destroy] do
    post 'attend',         on: :member
    post 'not_attend',     on: :member
    post 'share_facebook', on: :member
    get 'all',        on: :collection
    get 'my',         on: :collection  
    get 'near_city',    on: :collection
    get 'near_region',  on: :collection
    get 'near_country', on: :collection
    get 'public',     on: :collection
    get 'search',     on: :collection
  end

  resources :places, only: :index do
    get 'people',     on: :collection
    get 'change_regions',     on: :collection
  end


  resources :groups, only: [:new, :create] do
    get 'mine',       on: :collection, as: :my
    get 'users',      on: :member
    get 'members',    on: :member
    get 'about',      on: :member
    get 'groupusers', on: :collection
    get 'moderate',   on: :collection
    get 'settings',   on: :member
    # get 'discussion', on: :member
    get 'popular', on: :collection
    get 'recent', on: :collection
    get 'search',     on: :collection
    get 'council', on: :member
    get 'latest_discussions', on: :member
    get 'latest_activities',  on: :member
    post 'share_facebook', on: :member
    post 'join_group',  to: 'membership#create'
    delete 'removes_member', to: 'membership#remove'
    put 'add_as_group_leader', to: 'membership#add_as_group_leader'
    put 'remove_from_group_leader', to: 'membership#remove_from_group_leader'
    put 'block', to: 'membership#block_from_group'
    
    resources :discussions, only: [:new, :create, :show, :update] do
      resources :comments do
        post 'like', on: :collection
        
      end
    end
    
    resources :settings, only: [:create, :update]
  end

  resources :interests, only: [:index, :show, :new] do
    get 'members',    on: :member
    get 'follow',    on: :member
    get 'unfollow',    on: :member
    get 'fetch_interests', on: :collection
  end

  resources :users, only: [:show] do 
    resource  :profile, only: [:show, :edit, :update]
    resources :messages, only: [:create]
    resources :pictures, only: [:index, :create, :show, :destroy, :update] do
      resources :comments do
        post 'like', on: :collection
        
      end
      get 'upload_picture',    on: :collection
    end
    resources :activities
    resources :update_statuses
    
    post   '/friend_request',  to: 'friendship#create'
    post   '/accept',  to: 'friendship#accept', as: 'friend_request_accept'
    post   '/ignore',  to: 'friendship#ignore', as: 'friend_request_ignore'
    post   '/decline',  to: 'friendship#decline', as: 'friend_request_decline'
    get    '/friend_requests', to: 'friendship#friend_requests'
    get    '/messages', to: 'messages#messages_with_user', as: 'related_messages'
    
  end

  resource :authorization, only: [:destroy] 
  
  resources :comments, only: [:destroy] do
    post 'flag', on: :collection
  end

  
  
  
end

app/views/shared/_ads.html.haml
%ul.listA
  %li
    = image_tag 'thumb_placeholder2.jpg', width: 102, height: 103, alt: 'Thumbnail'
    %p Seshank - Here is where you can upload your own images and text to display to the users...
  %li
    = image_tag 'thumb_placeholder3.jpg', width: 102, height: 103, alt: 'Thumbnail'
    %p Seshank - Here is where you can upload your own images and text to display to the users...

  %li
    = image_tag 'thumb_placeholder4.jpg', width: 102, height: 103, alt: 'Thumbnail'
    %p Seshank - Here is where you can upload your own images and text to display to the users...

app/views/shared/_application_header.html.haml
%header.outwards
  .inwards


    %nav
      %ul
        %li{class: (yield(:navigation_item) === "Home") ? "on" : ""}
          = link_to 'Home', dashboard_path, title: 'Back to the Home Page', id: 'Home', accesskey: 'H'
        %li{class: (yield(:navigation_item) === "Events") ? "on" : ""}
          = link_to 'Events',    all_events_path,    accesskey: '1'
        %li{class: (yield(:navigation_item) === "Places") ? "on" : ""}
          = link_to 'Places',    places_path,    accesskey: '2'
        %li{class: (yield(:navigation_item) === "Groups") ? "on" : ""}
          = link_to 'Groups',  popular_groups_path,    accesskey: '3'
        %li{class: (yield(:navigation_item) === "Interests") ? "on" : ""}
          = link_to 'Interests', interests_path, accesskey: '4'

    #updates
      = link_to inbox_path, :class => "mail" do
        - unless current_user.received_messages.where('read_at is null').size == 0
          %span.meter= current_user.received_messages.where('read_at is null').size  
        

  

      .notifications
        %span.meter 
        %ul
          %h2
            Notifications
          <li><a href=""><span>3</span> new comments on your pictures</a></li>
          <li><a href=""><span>4</span> posts in a discussion you posted in</a></li>
          <li><a href=""><span>Rafaela Bing</span> commented <span>"Hey! Where have you been?"</span> on your profile</a></li>

      .settings
        %ul
          %h2
            Settings
          %li= link_to "View Profile", user_profile_path(current_user)
          %li= link_to "Edit Profile", edit_user_profile_path(current_user)
          %li= link_to "Account Settings", settings_path
          %li= link_to "Logout", destroy_user_session_path


    %aside
      %form{action: search_path, autocomplete: :off}

        <label for="header-search-query" class="placeholder">Search People, Events and Places</label>
        <input type="text" name="search_query" class="text" id="header-search-query" />
        <input type="submit" value="" id="header-submit"/>

app/views/shared/_devise_links.html.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  %br/

- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", root_path
  %br/

- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/

- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/

- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/

app/views/shared/_event_ads.html.haml
%ul.listA
  %li
    = image_tag 'thumb_placeholder2.jpg', width: 102, height: 103, alt: 'Thumbnail'
    .desc
      %h5 Advert Goes Here
      %p Seshank - Here is where you can upload your own images and text to display to the users...
  %li
    = image_tag 'thumb_placeholder3.jpg', width: 102, height: 103, alt: 'Thumbnail'
    .desc
      %h5 Advert Goes Here
      %p Seshank - Here is where you can upload your own images and text to display to the users...

  %li
    = image_tag 'thumb_placeholder4.jpg', width: 102, height: 103, alt: 'Thumbnail'
    .desc
      %h5 Advert Goes Here
      %p Seshank - Here is where you can upload your own images and text to display to the users...

app/views/shared/_favicons.html.haml
%link{rel: 'shortcut icon', href: image_path("logos/favicon.ico"), type: 'image/x-icon'}

app/views/shared/_flash.html.haml
.flashmessages
  .notice<
    %span.message
    %span.close x
  .warning<
    %span.message
    %span.close x

  .error<
    %span.message
    %span.close x

app/views/shared/_report.html.haml
.box
 %ul
  %li.report
   = link_to "Report #{page_name}", "#"
  - if page_name === "user"
   %li.block
    = link_to "Block user"

app/views/shared/_share.html.haml
.box.boxB
 %h3
  Share #{page_name}
 %ul.share-mini
  - if @facebook
   %li#facebook-sm
    - if page_name == "Event"
     = link_to "Share on Facebook", share_facebook_event_path(@event), :method => :post
    - if page_name == "Group" 
     = link_to "Share on Facebook", share_facebook_group_path(@group), :method => :post
    
  - if @twitter
   %li#twitter-sm
    = link_to "Share on Twitter", "#"
   
  - if @google
   %li#gplus-sm
    = link_to "Share on Google Plus", "#"

app/views/shared/_social_logins.html.haml
.social-wrap
 = link_to user_omniauth_authorize_path(:facebook) do
  %button.facebook{action: "#"}  
   Sign in
   %em
    w/
   Facebook
 = link_to user_omniauth_authorize_path(:twitter) do   
  %button.twitter{action: "#"}
   Sign in
   %em
    w/
   Twitter
 -# = link_to user_omniauth_authorize_path(:google_oauth2) do   
  -# %button.googleplus{action: "#"}
   -# Sign in
   -# %em
    -# w/
   -# Google

app/views/shared/_user_header.html.haml
- if current_user
  %div= link_to "Dashboard", dashboard_path
- else
  %div= link_to "Sign In", new_user_session_path