config/routes.rb
AroundYoga::Application.routes.draw do



  ## authorization
  devise_for :users,
    path: "",
    controllers: {
      sessions:           "users/sessions",
      passwords:          "users/passwords",
      confirmations:      "users/confirmations",
      omniauth_callbacks: "users/o_auth_callbacks",
      unlocks:            "users/unlocks",
      registrations:      "users/registrations"
    },
=begin
    skip: [
      :registrations
    ],
=end

    path_names: {
      sign_in:      'login',
      sign_out:     'logout',
      confirmation: 'verification',
    }


  post 'register',     to: "home#register", as: :register, format: false
  post 'create_user',  to: "home#create_user", as: :create_user, format: false

  match "/cities/autocomplete/:first_char" =>         "cities#autocomplete"
  match "/regions/fetch_regions/:country" =>          "regions#fetch_regions"
  match "/cities/fetch_cities/:country/:region" =>    "cities#fetch_cities"
  match "/interests/create/:interest" =>              "interests#create", :as => "creating"
  match "/interests/autocomplete/:first_char" =>      "interests#autocomplete"
  match "/events/autocomplete/:first_char" =>      "events#autocomplete"
  match "/groups/autocomplete/:first_char" =>      "groups#autocomplete"
  # match "/places/change_regions/:country" => "places#change_regions"

=begin  (current)
  ## resources
  resources :cities, format: false, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get   :autocomplete, on: :collection, format: false
  end
  

  resource  :strange,     format: false, path: :agree, only: [:edit, :update]
  resources :groups,      format: false
  resources :events,      format: false
  resources :discoveries, format: false
=end
  ## places
  resources :countries,   format: false, only: :show do
    resources :regions,   format: false, only: :show do
      resources :cities,  format: false, only: :show
    end
    get 'show_all_on_place',        on: :collection
  end
  

  ## static pages
  get 'about-us',         to: "pages#about_us",         as: :about_us,        format: false
  get 'contact-us',       to: "pages#contact_us",       as: :contact_us,      format: false
  get 'terms',            to: "pages#terms",            as: :terms,           format: false
  get 'advertisers',      to: "pages#advertisers",      as: :advertisers,     format: false
  get 'help',             to: "pages#help",             as: :help,            format: false
  get 'privacy-policy',   to: "pages#privacy_policy",   as: :privacy_policy,  format: false
  get 'user-agreement',   to: "pages#user_agreement",   as: :user_agreement,  format: false

  ## dashboard
  #current resource :dashboard, only: [:show], format: false
  get   '/dashboard',               to: 'dashboards#show'
  get   '/group_feed',              to: 'dashboards#group_feed'
  get   '/message',                 to: 'dashboards#message'
  get   '/search',                  to: 'dashboards#search'
  get   '/people',                  to: 'dashboards#people'
  get   '/pictures',                to: 'dashboards#pictures'
  get   '/picture',                 to: 'dashboards#picture'
  get   '/friendrequests',          to: 'friendship#friend_requests'
  get   '/upload_picture',          to: 'dashboards#upload_picture'
  get   '/settings',                to: 'dashboards#settings'
  post   '/update_settings',        to: 'dashboards#update_settings'
  get   '/connect_facebook',        to: 'dashboards#connect_facebook'
  get   '/inbox',                   to: 'messages#inbox'
  ## landing page
  root to: 'home#index'
  
  get '/manual_signup',             to: 'home#manual'
  
  ## resources
  resources :events, only: [:new, :create, :show, :destroy] do
    post 'attend',         on: :member
    post 'not_attend',     on: :member
    post 'share_facebook', on: :member
    get 'all',        on: :collection
    get 'my',         on: :collection  
    get 'near_city',    on: :collection
    get 'near_region',  on: :collection
    get 'near_country', on: :collection
    get 'public',     on: :collection
    get 'search',     on: :collection
  end

  resources :places, only: :index do
    get 'people',     on: :collection
    get 'change_regions',     on: :collection
  end


  resources :groups, only: [:new, :create] do
    get 'mine',       on: :collection, as: :my
    get 'users',      on: :member
    get 'members',    on: :member
    get 'about',      on: :member
    get 'groupusers', on: :collection
    get 'moderate',   on: :collection
    get 'settings',   on: :member
    # get 'discussion', on: :member
    get 'popular', on: :collection
    get 'recent', on: :collection
    get 'search',     on: :collection
    get 'council', on: :member
    get 'latest_discussions', on: :member
    get 'latest_activities',  on: :member
    post 'share_facebook', on: :member
    post 'join_group',  to: 'membership#create'
    delete 'removes_member', to: 'membership#remove'
    put 'add_as_group_leader', to: 'membership#add_as_group_leader'
    put 'remove_from_group_leader', to: 'membership#remove_from_group_leader'
    put 'block', to: 'membership#block_from_group'
    
    resources :discussions, only: [:new, :create, :show, :update] do
      resources :comments do
        post 'like', on: :collection
        
      end
    end
    
    resources :settings, only: [:create, :update]
  end

  resources :interests, only: [:index, :show, :new] do
    get 'members',    on: :member
    get 'follow',    on: :member
    get 'unfollow',    on: :member
    get 'fetch_interests', on: :collection
  end

  resources :users, only: [:show] do 
    resource  :profile, only: [:show, :edit, :update]
    resources :messages, only: [:create]
    resources :pictures, only: [:index, :create, :show, :destroy, :update] do
      resources :comments do
        post 'like', on: :collection
        
      end
      get 'upload_picture',    on: :collection
    end
    resources :activities
    resources :update_statuses
    
    post   '/friend_request',  to: 'friendship#create'
    post   '/accept',  to: 'friendship#accept', as: 'friend_request_accept'
    post   '/ignore',  to: 'friendship#ignore', as: 'friend_request_ignore'
    post   '/decline',  to: 'friendship#decline', as: 'friend_request_decline'
    get    '/friend_requests', to: 'friendship#friend_requests'
    get    '/messages', to: 'messages#messages_with_user', as: 'related_messages'
    
  end

  resource :authorization, only: [:destroy] 
  
  resources :comments, only: [:destroy] do
    post 'flag', on: :collection
  end

  
  
  
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :title, :avatar1, :caption, :permission
  
  belongs_to :user
  has_many   :comments, dependent: :destroy
  
  has_attached_file :avatar1, :styles => { :medium => "300x300>", :thumb => "27x27#" }
  
  def prev(user)
    Picture.first(:conditions => ['id < ? and user_id = ?', self.id, user.id], :order => 'id DESC')
  end

  def next(user)
    Picture.first(:conditions => ['id > ? and user_id = ?', self.id, user.id], :order => 'id ASC')
  end
 
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :authenticate_user!  
  before_filter :setup_user
  before_filter :check_access, :only => [:create, :destroy, :upload_picture, :updte]
  
   
  # GET /pictures
  # GET /pictures.json
  def index    
    @pictures = @user.pictures

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    
    @picture = Picture.find_by_id_and_user_id(params[:id], @user.id)
    
    @facebook = Authorization.where('user_id = ? and provider_id = ?',@user.id, 1000).first
    @twitter  = Authorization.where('user_id = ? and provider_id = ?',@user.id, 2000).first
    @google   = Authorization.where('user_id = ? and provider_id = ?',@user.id, 3000).first
    
    @comments = @picture.comments
    @comments_count = Comment.where(:picture_id => @picture.id, :like => nil).size
    @like_count = Comment.where(:picture_id => @picture.id, :like => true).size
    
    @editable_state = false
    
    respond_to do |format|
      format.html # show.html.erb
    end
  end



  # POST /pictures
  # POST /pictures.json
  def create
    
    unless params[:picture][:avatar1].nil?
      @user.pictures << Picture.new(params[:picture])
      picture = @user.pictures.last
      
      # create activity to upload this picture
      create_activity(current_user.id, "uploaded", "Picture", picture.id) 
      
      redirect_to :action => :index 
    else
      redirect_to :back
    end     
    
  end

 
  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find_by_id_and_user_id(params[:id], @user.id)
    @picture.destroy

    redirect_to :action => :index
     
  end
  
  def upload_picture
    @picture = Picture.new 

  end
  
  def update
    
    if request.xhr?
      puts "this is ajax!!!"
    else
      puts "this is not ajax!!!"
    end
    @picture = Picture.find_by_id_and_user_id(params[:id], @user.id)
    
    @picture.update_attributes(params[:picture])

    redirect_to :action => :show    
  end
  
  private    
  
  def check_access
    puts "check access!!!"
    setup_user
    # @user = User.find(params[:user_id])
    redirect_to :action => :index and return unless @user == current_user
  end  
end

app/helpers/pictures_helper.rb
module PicturesHelper

end

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.haml
#main.inwards.colgroup.colgroup1

 .col
  %hgroup

   %h1
    Pictures of
    = link_to @user.name, user_profile_path(@user)
   - if @user == current_user
    = link_to upload_picture_user_pictures_path(@user) do
     %button.btn.btnB.headingButton.pictureBtn.innerBtn{action: "#"}
      Upload Picture  
     
    
   %h2.spaceFix.location
    = @user.profile.place


  %section
   %ul.pictures
    - @pictures.each do |picture|
     %li
      = link_to image_tag(picture.avatar1.url, width: 180, height: 180, alt: :avatar), user_picture_path(@user, picture)
      %span.caption= picture.caption
      %span.time-info= distance_of_time_in_words_to_now(picture.created_at).to_s + ' ago ' + ' | ' + picture.created_at.to_date.to_formatted_s(:db)
       
    %hr.clear
   %hr.clear
 %aside
  = render partial: 'shared/event_ads'

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.haml
- content_for(:navigation_item) { 'Home' }
- content_for(:page_title) {"A Day at the Beach | Seshank Vemuri"}
#main.inwards.colgroup.colgroup1
 .col
  %hgroup
   %h1.lowerHeadline
    Pictures of
    = link_to @user.name, user_profile_path(@user)
   = link_to "Back to #{@user.name}'s Pictures", user_pictures_path(@user), id: "pictures-back"

  .picture_wrap
   = image_tag @picture.avatar1.url

  %section.discussion
   %div
    %span#edit_photo_caption
     = @picture.caption
     - if @user == current_user
      |
      = link_to "edit caption", "#", :id => "caption_edit"
    

  
  %ul.comments
   %div
    Comments    
    %span#comment-count 
     = @comments_count.to_s 
   %div.comment-wrap  
    - unless @comments.empty?    
     - @comments.each do |comment|
      - unless comment.body.nil? 
       = render :partial => 'comments/comment', :locals => {:comment => comment, :editable_state => @editable_state}   
   - unless @user == current_user      
    .comment-form-wrap
     %h3
      Post a new comment
     = form_for [@user, @picture, Comment.new], :remote => true, :html => {:class => "add-comment"} do |comment_f|
      = hidden_field_tag 'comment_type', 'picture'
      = comment_f.text_area :body
      = comment_f.submit "Add Comment", :class => "default_button"

 %aside
  .prev-next 
   %h1.prev 
    - if @picture.prev(@user).nil?
     << Prev
    - else  
     = link_to "<< Prev",  user_picture_path(@user, @picture.prev(@user))
   %h1.next
    - if @picture.next(@user).nil?
     Next >>
    - else  
     = link_to "Next >>",  user_picture_path(@user, @picture.next(@user))
         

  .box.boxB
   %h3
    Picture Information
   %ul.picInfo
    %li
     %span#comment-count 
      = @comments_count.to_s 
     Comments
    %li
     %span#like-count  
      = @like_count.to_s
     Likes
    %li
     Posted 
     = distance_of_time_in_words_to_now(@picture.created_at).to_s + ' ago '  
    - if @user == current_user 
     %li
      = link_to "Delete Picture", user_picture_path(@user, @picture), :method => :delete  
    - unless @user == current_user            
     %li.like
      - if Comment.where(:user_id => current_user.id, :picture_id => @picture.id, :like => true).empty? 
       = link_to "Like Picture", like_user_picture_comments_path(@user, @picture), :method => :post
      - else
       %p Like Picture
     
  = render :partial => "shared/share", :locals => {:page_name => "Picture", :user => @user}
  = render partial: 'shared/event_ads'
  = render :partial => "shared/report", :locals => {:page_name => "Picture"}
  

#caption_dialog
 %p.validateTips All form fields are required.
 
 = form_for [@user, @picture], :method => :put do |f|
  = f.label :caption
  = f.text_area :caption

app/views/pictures/upload_picture.html.haml
- content_for(:navigation_item) { 'Home' }
- content_for(:page_title) {"A Day at the Beach | Seshank Vemuri"}
#main.inwards.colgroup.colgroup1
 .col
  %hgroup
   %h1
    Upload Picture
  .target
   = image_tag "big_placeholder.jpg", {id: "imgTarget"}
  = form_for [@user, @picture], :html => { :id => "uploadHolder", :multipart => true } do |f|
   = f.file_field :avatar1
   %p>
   = f.label :caption
   = f.text_area :caption
   %p>
   = f.label :permission
   - array = ['friends only', 'everyone']
   = f.select :permission, options_for_select(array, @picture.permission)
   = f.submit "Upload", :class => "primaryButton block"

 %aside
  = render partial: 'shared/event_ads'