config/routes.rb
AroundYoga::Application.routes.draw do



  ## authorization
  devise_for :users,
    path: "",
    controllers: {
      sessions:           "users/sessions",
      passwords:          "users/passwords",
      confirmations:      "users/confirmations",
      omniauth_callbacks: "users/o_auth_callbacks",
      unlocks:            "users/unlocks",
      registrations:      "users/registrations"
    },
=begin
    skip: [
      :registrations
    ],
=end

    path_names: {
      sign_in:      'login',
      sign_out:     'logout',
      confirmation: 'verification',
    }


  post 'register',     to: "home#register", as: :register, format: false
  post 'create_user',  to: "home#create_user", as: :create_user, format: false

  match "/cities/autocomplete/:first_char" =>         "cities#autocomplete"
  match "/regions/fetch_regions/:country" =>          "regions#fetch_regions"
  match "/cities/fetch_cities/:country/:region" =>    "cities#fetch_cities"
  match "/interests/create/:interest" =>              "interests#create", :as => "creating"
  match "/interests/autocomplete/:first_char" =>      "interests#autocomplete"
  match "/events/autocomplete/:first_char" =>      "events#autocomplete"
  match "/groups/autocomplete/:first_char" =>      "groups#autocomplete"
  # match "/places/change_regions/:country" => "places#change_regions"

=begin  (current)
  ## resources
  resources :cities, format: false, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get   :autocomplete, on: :collection, format: false
  end
  

  resource  :strange,     format: false, path: :agree, only: [:edit, :update]
  resources :groups,      format: false
  resources :events,      format: false
  resources :discoveries, format: false
=end
  ## places
  resources :countries,   format: false, only: :show do
    resources :regions,   format: false, only: :show do
      resources :cities,  format: false, only: :show
    end
    get 'show_all_on_place',        on: :collection
  end
  

  ## static pages
  get 'about-us',         to: "pages#about_us",         as: :about_us,        format: false
  get 'contact-us',       to: "pages#contact_us",       as: :contact_us,      format: false
  get 'terms',            to: "pages#terms",            as: :terms,           format: false
  get 'advertisers',      to: "pages#advertisers",      as: :advertisers,     format: false
  get 'help',             to: "pages#help",             as: :help,            format: false
  get 'privacy-policy',   to: "pages#privacy_policy",   as: :privacy_policy,  format: false
  get 'user-agreement',   to: "pages#user_agreement",   as: :user_agreement,  format: false

  ## dashboard
  #current resource :dashboard, only: [:show], format: false
  get   '/dashboard',               to: 'dashboards#show'
  get   '/group_feed',              to: 'dashboards#group_feed'
  get   '/message',                 to: 'dashboards#message'
  get   '/search',                  to: 'dashboards#search'
  get   '/people',                  to: 'dashboards#people'
  get   '/pictures',                to: 'dashboards#pictures'
  get   '/picture',                 to: 'dashboards#picture'
  get   '/friendrequests',          to: 'friendship#friend_requests'
  get   '/upload_picture',          to: 'dashboards#upload_picture'
  get   '/settings',                to: 'dashboards#settings'
  post   '/update_settings',        to: 'dashboards#update_settings'
  get   '/connect_facebook',        to: 'dashboards#connect_facebook'
  get   '/inbox',                   to: 'messages#inbox'
  ## landing page
  root to: 'home#index'
  
  get '/manual_signup',             to: 'home#manual'
  
  ## resources
  resources :events, only: [:new, :create, :show, :destroy] do
    post 'attend',         on: :member
    post 'not_attend',     on: :member
    post 'share_facebook', on: :member
    get 'all',        on: :collection
    get 'my',         on: :collection  
    get 'near_city',    on: :collection
    get 'near_region',  on: :collection
    get 'near_country', on: :collection
    get 'public',     on: :collection
    get 'search',     on: :collection
  end

  resources :places, only: :index do
    get 'people',     on: :collection
    get 'change_regions',     on: :collection
  end


  resources :groups, only: [:new, :create] do
    get 'mine',       on: :collection, as: :my
    get 'users',      on: :member
    get 'members',    on: :member
    get 'about',      on: :member
    get 'groupusers', on: :collection
    get 'moderate',   on: :collection
    get 'settings',   on: :member
    # get 'discussion', on: :member
    get 'popular', on: :collection
    get 'recent', on: :collection
    get 'search',     on: :collection
    get 'council', on: :member
    get 'latest_discussions', on: :member
    get 'latest_activities',  on: :member
    post 'share_facebook', on: :member
    post 'join_group',  to: 'membership#create'
    delete 'removes_member', to: 'membership#remove'
    put 'add_as_group_leader', to: 'membership#add_as_group_leader'
    put 'remove_from_group_leader', to: 'membership#remove_from_group_leader'
    put 'block', to: 'membership#block_from_group'
    
    resources :discussions, only: [:new, :create, :show, :update] do
      resources :comments do
        post 'like', on: :collection
        
      end
    end
    
    resources :settings, only: [:create, :update]
  end

  resources :interests, only: [:index, :show, :new] do
    get 'members',    on: :member
    get 'follow',    on: :member
    get 'unfollow',    on: :member
    get 'fetch_interests', on: :collection
  end

  resources :users, only: [:show] do 
    resource  :profile, only: [:show, :edit, :update]
    resources :messages, only: [:create]
    resources :pictures, only: [:index, :create, :show, :destroy, :update] do
      resources :comments do
        post 'like', on: :collection
        
      end
      get 'upload_picture',    on: :collection
    end
    resources :activities
    resources :update_statuses
    
    post   '/friend_request',  to: 'friendship#create'
    post   '/accept',  to: 'friendship#accept', as: 'friend_request_accept'
    post   '/ignore',  to: 'friendship#ignore', as: 'friend_request_ignore'
    post   '/decline',  to: 'friendship#decline', as: 'friend_request_decline'
    get    '/friend_requests', to: 'friendship#friend_requests'
    get    '/messages', to: 'messages#messages_with_user', as: 'related_messages'
    
  end

  resource :authorization, only: [:destroy] 
  
  resources :comments, only: [:destroy] do
    post 'flag', on: :collection
  end

  
  
  
end

app/controllers/dashboards_controller.rb
#current class DashboardsController < SecureController
class DashboardsController < ApplicationController
 before_filter :authenticate_user!  

  ## Application
  def show
    @user = current_user
    
    @friends = @user.friends
    @my_activities = @user.activities.order('created_at DESC')
    
    @friend_activities = []
    
    @friends.each do |friend|
      @friend_activities = @friend_activities + friend.activities
    end    
    
    @activities = @my_activities + @friend_activities
    
    #update status
    @update_status = UpdateStatus.new
  end 
  
  def group_feed
    @user = current_user
    
    @friends = @user.friends
    @my_activities = @user.activities.where(:target => ["Group", "Comment"]).order('created_at DESC')
    
    @friend_activities = []
    
    @friends.each do |friend|
      @friend_activities = @friend_activities + friend.activities.where(:target => ["Group", "Comment"]).order('created_at DESC')
    end    
    
    activities = @my_activities + @friend_activities
    
    # remove picture comment activity
    @activities = activities
    activities.each do |act|
      if act.target == "Comment"
        if Comment.find(act.target_id).discussion_id.nil?
          @activities = @activities - [act]
        end
      end
    end
    
    #update status
    @update_status = UpdateStatus.new
    
    render :show
    
  end

  def places
    
  end

  def reset_password
  end

  def interests
  end

  def upload_picture
  end
  
  def search
    query = params[:search_query]
    if query.empty?
      redirect_to :back and return
    else
      @peoples = User.where('lower(name) like ?', "%#{query.downcase}%").order('current_sign_in_at DESC')
      
      @events = Event.where('lower(name) like ?', "%#{query.downcase}%").order(:name)
      @groups = Group.where('lower(name) like ?', "%#{query.downcase}%").order(:name)
      @countries = Country.where('lower(name) like ?', "%#{query.downcase}%")
      @regions = Region.where('lower(name) like ?', "%#{query.downcase}%")
      @cities = City.where('lower(name) like ?', "%#{query.downcase}%")
    end
 
  end


  def settings
    @user = current_user
    auth = request.env["omniauth.auth"]
    puts auth
    @facebook = Authorization.where('user_id = ? and provider_id = ?',current_user.id, 1000).first
    @twitter  = Authorization.where('user_id = ? and provider_id = ?',current_user.id, 2000).first
    @google   = Authorization.where('user_id = ? and provider_id = ?',current_user.id, 3000).first
  end
  
  def update_settings
    puts "okokokokokokokokokokokokokokokokokokokokokokokokokokoko"
    email = params[:email]
    if email.empty?
      puts "email is empty!!!!!!!!!!!!!!!!!!"
      redirect_to :back and return
    end
    user = current_user
    user.email = email
    puts "email changed? " + user.changed?.to_s
    puts "email changed" if user.email_changed?
    puts "email: " + email.to_s
    
    begin
      if !user.email.empty? && user.email_changed?
        user.send_confirmation_instructions  
      end
      
    rescue => e
      error = e
      puts error
    ensure
      #
    end    
    redirect_to :back    
  end
  
  def connect_facebook
    puts "start facebook"
    begin
      auth = request.env["omniauth.auth"]
      puts auth
      @provider_id = OAuthProviders.symbol_to_id(provider)
      @uid = auth.uid
      
      authorization = Authorization.joins( :user ).where( provider_id: @provider_id, uid: @uid ).lock.first
      @user = User.new
      if !authorization        
        @user.name = auth.info.name.to_s        
        @user.email = auth.info.email.to_s unless provider.to_s == "twitter"
        render :action => "confirm" and return
      else
        @user = authorization.user
      end      
    rescue => e
      error = e
      puts error
    ensure
      #
    end

  end

  def resend_unlock
  end

  def resend_instructions
  end

  def people
    @user = current_user
    @friends = @user.friends
  end

  def pictures
  end

  def picture
  end

end

app/views/dashboards/people.html.haml
#main.inwards.colgroup.colgroup2
 %hgroup
  %h1
   People
  %h2= '(' + @friends.size.to_s + ')'
 %div.col
  %section.box.boxC.peopleList.noBorder
   %ul.listE.smallList
    - @friends.each do |friend|
     %li
      = image_tag friend.avatar.url
      %h2
       = link_to friend.name, user_profile_path(friend)
      %strong= friend.profile.place
 %aside
  = render partial: 'shared/event_ads'

app/views/dashboards/search.html.haml
#main.inwards.colgroup.colgroup2
  %hgroup
    %h1 Search Results

  .col
    %section.box.boxC.namecards.noScroll
      %h2 
        People 
        %small= "(#{@peoples.size})"

      %ul.listE
        - @peoples.each do |people|
          %li
            = image_tag people.avatar.url, width: 81, height: 81, alt: :avatar
            %h2= link_to people.name, user_profile_path(people)
            %strong= people.profile.place
      </ul>
      -# = link_to "See All", "#", class: :loadMore


    %section.box.boxC

      %h2 
        Events
        %small= "(#{@events.size})"

      %ul.listC
        - @events.each do |event|
          %li
            .inner
              %time<
                %span= event.started_at.strftime("%A")
                %span.cal
                  %span= event.started_at.strftime("%b")
                  %span= event.started_at.day
    
              %h2= link_to event.name, event_path(event)
              %time= event.started_at.strftime("%A %d %B, %I%P") + " - " + event.ended_at.strftime("%A %d %B,%I%P")   
              
              %address
                %span= event.address

    %section.box.boxC
      %h2
        Groups
        %small= "(#{@groups.size})"
      %ul.listC.listD
        - @groups.each do |group|
          - unless group.owners.empty?
            %li
              .inner
                -# %aside
                -# = image_tag group.avatar.url, width: 80, height: 80, alt: :avatar
                -# %span
                  -# By
                  -# = link_to group.owners.first.name, user_profile_path(group.owners.first)
                -# %time= distance_of_time_in_words_to_now(group.created_at).to_s + ' ago '
                
                %section
                  %h2= link_to group.name, latest_discussions_group_path(group)
                  %p= group.description
  
                  %footer
                    %menu
                      <li class="follow"><a href="ajax.php" data-opposite-action="Unfollow" class="toggle-action">Follow</a>
                      %li.comment
                        = link_to "Comment (#{comments_count(group)})", '#'
  
  
                    - unless group.discussions.empty?
                      %span.meta
                        Last post by
                        = link_to group.discussions.last.user.name, user_profile_path(group.discussions.last.user)
                        at
                        %time= group.discussions.last.created_at.to_time.strftime('%I:%P')
                      


    %section.box.boxC
      %h2
        Places
      .colgroup
        .col
          %h3
            Country
          %ul
            - @countries.each do |country|
              %li= link_to country.name, country_path(country) 
              
          %h3
            Region
          %ul
            - @regions.each do |region|
              %li= link_to region.name, country_region_path(region.country, region)
                
          %h3
            City      
          %ul
            - @cities.each do |city|
              %li= link_to city.name, country_region_city_path(city.country, city.region, city)
          
  %aside
    = render partial: 'shared/event_ads'             

app/views/dashboards/settings.html.haml
- content_for(:navigation_item) { 'Home' }
#main.inwards.colgroup.colgroup1
 %hgroup.leftFix
  %h1
   Account Settings
 #form_wrap
  = form_tag('/update_settings', :class => "form_default") do
   = label_tag(:email, "Email:")
   = email_field_tag :email, @user.email
   %fieldset
    %label{for: "radio1"} Lorem ipsum dolor
    %input#radio1{type: "radio", name: "group1", value: "On"}
     On
    %input{type: "radio", name: "group1", value: "Off"}
     Off
   %fieldset
    %label{for: "radio1"} Lorem ipsum dolor
    %input#radio1{type: "radio", name: "group1", value: "On"}
     On
    %input{type: "radio", name: "group1", value: "Off"}
     Off
   %fieldset
    %label{for: "radio1"} Lorem ipsum dolor
    %input#radio1{type: "radio", name: "group1", value: "On"}
     On
    %input{type: "radio", name: "group1", value: "Off"}
     Off
   .social-wrap
    - if @facebook 
     Facebook: 
     = link_to @facebook.name, @facebook.url
     = link_to "Disconnect", authorization_path(@facebook), :method => "delete"
    - else
     = button_tag "Connect to Facebook", :type => 'button',  :class => "facebook"    
    %br/ 
    
    - if @twitter 
     Twitter: 
     = link_to @twitter.name, @twitter.url
     = link_to "Disconnect", authorization_path(@twitter), :method => "delete"
    - else
     = button_tag "Connect to Twitter", :type => 'button',  :class => "twitter"
    %br/
      
    - if @google
     Google:  
     = link_to @google.name, @google.url
     = link_to "Disconnect", authorization_path(@google), :method => "delete"
    - else
     = button_tag "Connect to Google", :type => 'button',  :class => "googleplus"

   = button_tag "Save", :type => 'submit',  :class => "primaryButton block"

app/views/dashboards/show.html.haml
- content_for(:page_title) { 'My Dashboard' }
- content_for(:navigation_item) { 'Home' }

#main.inwards.colgroup.colgroup1
  .col
    -# %form.update-status{method: :post, action: '#'}
    = form_for [@user, @update_status] do |f|
      = f.text_area :context
      = f.submit "Post"
      
    .book.bookA
      %nav
        %ul
          %li.on
            = link_to "All", dashboard_path
          %li  
            = link_to "Groups", group_feed_path
          

      %section
        %ul.listH
          - @activities.each do |activity|
            %li
              %aside
                = image_tag activity.user.avatar.url, width: 54, height: 54, alt: :avatar
                %time= activity.created_at.strftime("%B %d")
  
              %article
                %h5= link_to activity.user.name, user_profile_path(activity.user)
                %p= display_activity(activity)



  %aside
    %section.box
      %h2<



      %menu.dashboard
        %li= link_to 'Inbox', inbox_path
        %li= link_to 'Friends', people_path
        %li= link_to 'Upload Picture', upload_picture_user_pictures_path(@user)
        %li= link_to 'My Groups', my_groups_path
        %li= link_to 'My Events', my_events_path
        %li<
          = link_to "Friend Requests (#{@user.requested_friends.size})", user_friend_requests_path(@user)

    = render partial: 'shared/ads'